export const ROLES = {
  PATIENT: 'PATIENT',
  PHYSICIAN: 'PHYSICIAN',
  LAB_PHYSICIAN: 'LAB_PHYSICIAN',
  IMAGE_PHYSICIAN: 'IMAGE_PHYSICIAN',
};

export const DUTIES = {
  GENERAL_EXAMINATION: 'Khám sơ bộ',
  SPECIALIST_EXAMINATION: 'Khám chuyên khoa',
};

export const SERVICE_TYPES = {
  GENERAL_CONSULTATION: 'Sơ bộ',
  SPECIALIST_CONSULTATION: 'Chuyên khoa',
  LABORATORY_TEST: 'Xét nghiệm',
  IMAGING_SCAN: 'Chụp chiếu',
};
